### ISSUE TITLE
Mock API controller function "contacts. getContact()" to handle Swagger defined GET route

### ISSUE THREAD

**Issue by nfloersch** [codeforbtv/hsda-cfbtv#11]
The /contacts/{contact_id}/ route in the YAML is defined [here](https://github.com/codeforbtv/hsda-cfbtv/blob/852c96ce79815e0f82ffa029a9f7519d05fd3cb1/api/swagger/swagger.yaml#L106):
```
 /contacts/{contact_id}/:
    x-swagger-router-controller: contacts
    get:
      summary: Get contact
      description: Returns a contact entry by its Id
      operationId: getContact
```

The YAML file defines the route (` /contacts/{contact_id}/`), controller (`x-swagger-router-controller: contacts`), and function name (`operationId: getContact`) that will be called for the GET verb.

https://github.com/codeforbtv/hsda-cfbtv/blob/852c96ce79815e0f82ffa029a9f7519d05fd3cb1/api/swagger/swagger.yaml#L290

For the contacts controller, we need to mock up a getContactComplete() function that takes in the parameters of the function as defined in the YAML, and responds with a JSON object that reflects those values back to the caller.

In the [YAML the params are listed](https://github.com/codeforbtv/hsda-cfbtv/blob/ce6e86327229498a9989643f86834509be955f1f/api/swagger/swagger.yaml#L294) as:
```
parameters:
        - in: path
          required: true
          type: string
          name: contact_id
          description: 'The contact id.'
```

This can be done fixing the body of this placeholder function located in [file](https://github.com/codeforbtv/hsda-cfbtv/blob/master/api/controllers/contacts.js):
```
function getContact(req, res) {
  // variables defined in the Swagger document can be referenced using req.swagger.params.{parameter_name}
  var name = req.swagger.params.name.value || 'stranger';
  var hello = util.format('Hello, %s!', name);

  // this sends back a JSON response which is a single string
  res.json(hello);
}
```

To see an example solution to a similar problem to get you started, view issue #1
