### ISSUE TITLE
Mock API controller function "contacts.listContactsComplete()" to handle Swagger defined GET route

### ISSUE THREAD

**Issue by nfloersch** [codeforbtv/hsda-cfbtv#4]
The contacts/complete route in the YAML is defined [here](https://github.com/codeforbtv/hsda-cfbtv/blob/852c96ce79815e0f82ffa029a9f7519d05fd3cb1/api/swagger/swagger.yaml#L106):
```
/contacts/complete/:
   x-swagger-router-controller: contacts
    get:
      summary: Get all contacts with full details
      description: Returns a list of contacts with full details and filtering support
      operationId: listContactsComplete
```

The YAML file defines the route (`/contacts/complete/`), controller (`x-swagger-router-controller: contacts`), and function name (`operationId: listContactsComplete`) that will be called for the GET verb.

https://github.com/codeforbtv/hsda-cfbtv/blob/852c96ce79815e0f82ffa029a9f7519d05fd3cb1/api/swagger/swagger.yaml#L108

For the contacts controller, we need to mock up a listContactsComplete() function that takes in the parameters of the function as defined in the YAML, and responds with a JSON object that reflects those values back to the caller.

In the [YAML the params are listed](https://github.com/codeforbtv/hsda-cfbtv/blob/ce6e86327229498a9989643f86834509be955f1f/api/swagger/swagger.yaml#L112) as:
```
parameters:
        - in: query
          type: string
          name: query
          description: A query to filter list by (up to provider to determine what to search)
        - in: query
          type: string
          name: queries
          description: A comma separate list of queries with specific fields.
        - in: query
          type: number
          name: page
          default: 0
          description: The particular page of results.
        - in: query
          type: number
          name: per_page
          default: 25
          description: Number of records to return per page, up to 100.
        - in: query
          type: string
          name: sort_by
          default: name
          description: Which field to sort by.
        - in: query
          type: string
          name: order
          default: asc
          description: Which order to sort by (asc,desc).
```

This can be done fixing the body of this placeholder function located in [file](https://github.com/codeforbtv/hsda-cfbtv/blob/master/api/controllers/contacts.js):
```
function listContactsComplete(req, res) {
  // variables defined in the Swagger document can be referenced using req.swagger.params.{parameter_name}
  var name = req.swagger.params.name.value || 'stranger';
  var hello = util.format('Hello, %s!', name);

  // this sends back a JSON response which is a single string
  res.json(hello);
}
```

To see an example solution to a similar problem to get you started, view issue #1
